# -*- coding: utf-8 -*-
"""Данни за дневния хороскоп по зодия (12-те знака).

Всеки знак има SEO slug, българско име, глиф, дати, стихия, модалност,
управител и ключови думи. Използва се от рутовете /horoskop/{slug} и от
началната страница (лентата с 12-те знака).
"""

# Редът е зодиакален (от Овен), съвпада с translations.ZODIAC_ORDER.
ZODIAC_SIGNS = [
    {
        "sign": "Aries",
        "slug": "oven",
        "name": "Овен",
        "glyph": "♈",
        "dates": "21 март – 19 април",
        "element": "Огън",
        "element_key": "fire",
        "modality": "Кардинален",
        "modality_key": "cardinal",
        "ruler": "Марс",
        "keywords": "дневен хороскоп овен, хороскоп овен днес, овен днес, зодия овен",
    },
    {
        "sign": "Taurus",
        "slug": "telec",
        "name": "Телец",
        "glyph": "♉",
        "dates": "20 април – 20 май",
        "element": "Земя",
        "element_key": "earth",
        "modality": "Фиксиран",
        "modality_key": "fixed",
        "ruler": "Венера",
        "keywords": "дневен хороскоп телец, хороскоп телец днес, телец днес, зодия телец",
    },
    {
        "sign": "Gemini",
        "slug": "bliznaci",
        "name": "Близнаци",
        "glyph": "♊",
        "dates": "21 май – 20 юни",
        "element": "Въздух",
        "element_key": "air",
        "modality": "Променлив",
        "modality_key": "mutable",
        "ruler": "Меркурий",
        "keywords": "дневен хороскоп близнаци, хороскоп близнаци днес, близнаци днес, зодия близнаци",
    },
    {
        "sign": "Cancer",
        "slug": "rak",
        "name": "Рак",
        "glyph": "♋",
        "dates": "21 юни – 22 юли",
        "element": "Вода",
        "element_key": "water",
        "modality": "Кардинален",
        "modality_key": "cardinal",
        "ruler": "Луна",
        "keywords": "дневен хороскоп рак, хороскоп рак днес, рак днес, зодия рак",
    },
    {
        "sign": "Leo",
        "slug": "lav",
        "name": "Лъв",
        "glyph": "♌",
        "dates": "23 юли – 22 август",
        "element": "Огън",
        "element_key": "fire",
        "modality": "Фиксиран",
        "modality_key": "fixed",
        "ruler": "Слънце",
        "keywords": "дневен хороскоп лъв, хороскоп лъв днес, лъв днес, зодия лъв",
    },
    {
        "sign": "Virgo",
        "slug": "deva",
        "name": "Дева",
        "glyph": "♍",
        "dates": "23 август – 22 септември",
        "element": "Земя",
        "element_key": "earth",
        "modality": "Променлив",
        "modality_key": "mutable",
        "ruler": "Меркурий",
        "keywords": "дневен хороскоп дева, хороскоп дева днес, дева днес, зодия дева",
    },
    {
        "sign": "Libra",
        "slug": "vezni",
        "name": "Везни",
        "glyph": "♎",
        "dates": "23 септември – 22 октомври",
        "element": "Въздух",
        "element_key": "air",
        "modality": "Кардинален",
        "modality_key": "cardinal",
        "ruler": "Венера",
        "keywords": "дневен хороскоп везни, хороскоп везни днес, везни днес, зодия везни",
    },
    {
        "sign": "Scorpio",
        "slug": "skorpion",
        "name": "Скорпион",
        "glyph": "♏",
        "dates": "23 октомври – 21 ноември",
        "element": "Вода",
        "element_key": "water",
        "modality": "Фиксиран",
        "modality_key": "fixed",
        "ruler": "Плутон",
        "keywords": "дневен хороскоп скорпион, хороскоп скорпион днес, скорпион днес, зодия скорпион",
    },
    {
        "sign": "Sagittarius",
        "slug": "strelec",
        "name": "Стрелец",
        "glyph": "♐",
        "dates": "22 ноември – 21 декември",
        "element": "Огън",
        "element_key": "fire",
        "modality": "Променлив",
        "modality_key": "mutable",
        "ruler": "Юпитер",
        "keywords": "дневен хороскоп стрелец, хороскоп стрелец днес, стрелец днес, зодия стрелец",
    },
    {
        "sign": "Capricorn",
        "slug": "kozirog",
        "name": "Козирог",
        "glyph": "♑",
        "dates": "22 декември – 19 януари",
        "element": "Земя",
        "element_key": "earth",
        "modality": "Кардинален",
        "modality_key": "cardinal",
        "ruler": "Сатурн",
        "keywords": "дневен хороскоп козирог, хороскоп козирог днес, козирог днес, зодия козирог",
    },
    {
        "sign": "Aquarius",
        "slug": "vodoley",
        "name": "Водолей",
        "glyph": "♒",
        "dates": "20 януари – 18 февруари",
        "element": "Въздух",
        "element_key": "air",
        "modality": "Фиксиран",
        "modality_key": "fixed",
        "ruler": "Уран",
        "keywords": "дневен хороскоп водолей, хороскоп водолей днес, водолей днес, зодия водолей",
    },
    {
        "sign": "Pisces",
        "slug": "ribi",
        "name": "Риби",
        "glyph": "♓",
        "dates": "19 февруари – 20 март",
        "element": "Вода",
        "element_key": "water",
        "modality": "Променлив",
        "modality_key": "mutable",
        "ruler": "Нептун",
        "keywords": "дневен хороскоп риби, хороскоп риби днес, риби днес, зодия риби",
    },
]

ZODIAC_BY_SLUG = {s["slug"]: s for s in ZODIAC_SIGNS}
ZODIAC_BY_SIGN = {s["sign"]: s for s in ZODIAC_SIGNS}
